<?php

/**
 * Copyright © Rob Aimes - https://aimes.dev/
 * https://github.com/robaimes
 */

use Aimes\NativeExperience\Scope\Config;
use Aimes\NativeExperience\ViewModel\BatteryLevel;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Config $config */
/** @var BatteryLevel $batteryViewModel */
$config = $block->getConfig();
$batteryViewModel = $block->getBatteryViewModel();

if ($batteryViewModel->isCustomerLoggedIn()) {
    return;
}
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Aimes_NativeExperience/js/battery-status": {
                "low_battery_percentage": "<?= $escaper->escapeJs($config->getBatteryLowLevelWarning()) ?>",
                "low_battery_message": "<?= $escaper->escapeJs($batteryViewModel->getGuestBatteryMessage()) ?>"
            }
        }
    }
</script>
