<?php

/**
 * Copyright © Rob Aimes - https://aimes.dev/
 * https://github.com/robaimes
 */

use Aimes\NativeExperience\Scope\Config;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Config $config */
$config = $block->getConfig();
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Aimes_NativeExperience/js/online-status": {
                "online_message": "<?= $escaper->escapeJs($config->getNetworkStatusOnlineMessage()) ?>",
                "offline_message": "<?= $escaper->escapeJs($config->getNetworkStatusOfflineMessage()) ?>"
            }
        }
    }
</script>
